// Shared test helper: generate a self-signed Ed25519 cert + key into temp files
// using OpenSSL directly (no ca_generate, no CLI). Used by the SSL test
// fixtures (test_http_server_ssl, test_tcp_transport_ssl, test_ws_transport_ssl)
// so they don't depend on pre-existing certs/leaf_cert.pem.

#ifndef TEST_SSL_CERTS_H
#define TEST_SSL_CERTS_H

#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/asn1.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Generate a self-signed Ed25519 certificate + private key into temp files.
// Returns 0 on success and writes the paths to *cert_path / *key_path
// (caller must free the path strings + unlink the files). Returns -1 on failure.
static int test_generate_ssl_certs(char** cert_path, char** key_path) {
  if (cert_path == NULL || key_path == NULL) return -1;
  *cert_path = NULL;
  *key_path = NULL;

  // Generate an Ed25519 key pair.
  EVP_PKEY_CTX* pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_ED25519, NULL);
  if (pctx == NULL) return -1;
  if (EVP_PKEY_keygen_init(pctx) <= 0) { EVP_PKEY_CTX_free(pctx); return -1; }
  EVP_PKEY* pkey = NULL;
  if (EVP_PKEY_keygen(pctx, &pkey) <= 0) { EVP_PKEY_CTX_free(pctx); return -1; }
  EVP_PKEY_CTX_free(pctx);

  // Build a self-signed certificate.
  X509* cert = X509_new();
  if (cert == NULL) { EVP_PKEY_free(pkey); return -1; }
  X509_set_version(cert, 2);  // v3
  ASN1_INTEGER_set(X509_get_serialNumber(cert), 1);
  X509_gmtime_adj(X509_get_notBefore(cert), 0);
  X509_gmtime_adj(X509_get_notAfter(cert), 3650L * 86400);
  X509_set_pubkey(cert, pkey);
  X509_NAME* name = X509_get_subject_name(cert);
  X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, (const unsigned char*)"test", -1, -1, 0);
  X509_set_issuer_name(cert, name);
  if (X509_sign(cert, pkey, NULL) == 0) {  // Ed25519: NULL digest (no prehash)
    X509_free(cert); EVP_PKEY_free(pkey); return -1;
  }

  // Write the cert + key to temp files.
  char cert_tmpl[] = "/tmp/test_ssl_cert_XXXXXX";
  char key_tmpl[] = "/tmp/test_ssl_key_XXXXXX";
  int cert_fd = mkstemp(cert_tmpl);
  int key_fd = mkstemp(key_tmpl);
  if (cert_fd < 0 || key_fd < 0) {
    if (cert_fd >= 0) { close(cert_fd); unlink(cert_tmpl); }
    if (key_fd >= 0) { close(key_fd); unlink(key_tmpl); }
    X509_free(cert); EVP_PKEY_free(pkey); return -1;
  }
  close(cert_fd);
  close(key_fd);

  BIO* cert_bio = BIO_new_file(cert_tmpl, "w");
  if (cert_bio == NULL) { unlink(cert_tmpl); unlink(key_tmpl); X509_free(cert); EVP_PKEY_free(pkey); return -1; }
  PEM_write_bio_X509(cert_bio, cert);
  BIO_free(cert_bio);

  BIO* key_bio = BIO_new_file(key_tmpl, "w");
  if (key_bio == NULL) { unlink(cert_tmpl); unlink(key_tmpl); X509_free(cert); EVP_PKEY_free(pkey); return -1; }
  PEM_write_bio_PrivateKey(key_bio, pkey, NULL, NULL, 0, NULL, NULL);
  BIO_free(key_bio);

  X509_free(cert);
  EVP_PKEY_free(pkey);

  *cert_path = strdup(cert_tmpl);
  *key_path = strdup(key_tmpl);
  if (*cert_path == NULL || *key_path == NULL) {
    free(*cert_path); free(*key_path);
    unlink(cert_tmpl); unlink(key_tmpl);
    return -1;
  }
  return 0;
}

// Clean up the temp cert + key files generated by test_generate_ssl_certs.
static void test_cleanup_ssl_certs(const char* cert_path, const char* key_path) {
  if (cert_path != NULL) { unlink(cert_path); free((void*)cert_path); }
  if (key_path != NULL) { unlink(key_path); free((void*)key_path); }
}

#endif // TEST_SSL_CERTS_H