//
// Created by victor on 5/6/25.
//

#ifndef OFFS_MESSAGE_H
#define OFFS_MESSAGE_H

#include <stdint.h>

typedef enum message_type_e {
  SECTION_WRITE = 0,
  SECTION_READ,
  SECTION_DEALLOCATE,
  SECTION_SAVE_META,
  SECTION_CLOSE,
  SECTIONS_WRITE,
  SECTIONS_READ,
  SECTIONS_DEALLOCATE,
  SECTIONS_SECTION_FULL,
  SECTIONS_WRITE_COMPLETE,
  SECTIONS_READ_COMPLETE,
  SECTIONS_DEALLOCATE_COMPLETE,
  CACHE_GET,
  CACHE_PUT,
  CACHE_REMOVE,
  CACHE_BLOCK_LOADED,
  TIMER_SET,
  TIMER_CANCEL,
  TIMER_DEBOUNCE,
  INDEX_SAVE,
  SECTION_WRITE_META,
  READABLE_PUSH,
  WRITEABLE_WRITE,
  CLOSE_STREAM,
  READABLE_PULL,
  DEFERRED_DEREF,
  SECTION_WRITE_COMPLETE,
  SECTION_READ_COMPLETE,
  SECTION_DEALLOCATE_COMPLETE
} message_type_e;

typedef struct message_t {
  uint32_t type;
  void* payload;
  void (*payload_destroy)(void*);
} message_t;

#endif // OFFS_MESSAGE_H
