//
// Created by victor on 5/6/25.
//

#ifndef OFFS_MESSAGE_H
#define OFFS_MESSAGE_H

#include <stdint.h>

typedef enum message_type_e {
  SECTION_WRITE = 0,
  SECTION_READ,
  SECTION_DEALLOCATE,
  SECTION_SAVE_META,
  SECTION_CLOSE,
  SECTIONS_WRITE,
  SECTIONS_READ,
  SECTIONS_DEALLOCATE,
  SECTIONS_SECTION_FULL,
  SECTIONS_WRITE_COMPLETE,
  SECTIONS_READ_COMPLETE,
  SECTIONS_DEALLOCATE_COMPLETE,
  CACHE_GET,
  CACHE_PUT,
  CACHE_REMOVE,
  CACHE_BLOCK_LOADED,
  TIMER_SET,
  TIMER_CANCEL,
  TIMER_DEBOUNCE,
  INDEX_SAVE,
  SECTION_WRITE_META,
  READABLE_PUSH,
  READABLE_READ,
  READABLE_READ_COMPLETE,
  WRITEABLE_WRITE,
  CLOSE_STREAM,
  READABLE_PULL,
  DEFERRED_DEREF,
  TUPLE_CACHE_GET,
  TUPLE_CACHE_PUT,
  TUPLE_CACHE_REMOVE,
  TUPLE_CACHE_CONTAINS,
  TUPLE_CACHE_SIZE,
  OFF_STREAM_WRITE,
  WRITEABLE_FINALIZE,
  WRITEABLE_DESCRIPTOR_WRITE,
  BLOCK_RECIPE_PULL,
  RECIPE_BLOCK_DATA,
  RECIPE_ROTATE,
  SECTION_WRITE_COMPLETE,
  SECTION_READ_COMPLETE,
  SECTION_DEALLOCATE_COMPLETE,
  STREAM_NOTIFY,
  /* Async result messages — sent back to reply_to actor */
  SECTION_READ_RESULT,
  SECTION_WRITE_RESULT,
  SECTION_DEALLOCATE_RESULT,
  SECTIONS_READ_RESULT,
  SECTIONS_WRITE_RESULT,
  SECTIONS_DEALLOCATE_RESULT,
  CACHE_GET_RESULT,
  CACHE_PUT_RESULT,
  CACHE_REMOVE_RESULT,
  TUPLE_CACHE_GET_RESULT,
  /* HTTP connection messages */
  HTTP_CONNECTION_DATA,
  HTTP_CONNECTION_HANGUP,
  HTTP_CONNECTION_ERROR,
  HTTP_CONNECTION_WRITE,
  HTTP_CONNECTION_WRITABLE,
  HTTP_CONNECTION_CLOSE,
  /* HTTP server watcher messages */
  HTTP_SERVER_UPDATE_WATCHER,
  HTTP_SERVER_STOP_WATCHER,
  /* OFD cache resolve messages */
  OFD_CACHE_RESOLVE,
  OFD_CACHE_RESOLVE_RESULT,
  /* Stream actor messages */
  STREAM_SUBSCRIBE,
  STREAM_UNSUBSCRIBE,
  STREAM_DEACTIVATE,
  STREAM_PIPE,
  STREAM_PIPED,
  STREAM_CLOSE_HANDLER,
  STREAM_SET_PULLING,
  /* Network messages */
  NETWORK_PING,
  NETWORK_PING_RESPONSE,
  NETWORK_PING_CAPACITY,
  NETWORK_PING_CAPACITY_RESPONSE,
  NETWORK_PING_BLOCK,
  NETWORK_PING_BLOCK_RESPONSE,
  NETWORK_FIND_BLOCK,
  NETWORK_FIND_BLOCK_RESPONSE,
  NETWORK_FIND_NODE,
  NETWORK_FIND_NODE_RESPONSE,
  NETWORK_STORE_BLOCK,
  NETWORK_STORE_BLOCK_RESPONSE,
  NETWORK_SEEKING_BLOCKS,
  NETWORK_SEEKING_BLOCKS_RESPONSE,
  NETWORK_RANK_BLOCK,
  NETWORK_RECALL_BLOCK,
  NETWORK_RECALL_ACCEPT,
  NETWORK_RECALL_DECLINE,
  NETWORK_RATE_LIMITED,
  NETWORK_EABF_EXPIRE,
  NETWORK_GOSSIP_TICK,
  NETWORK_GOSSIP_EXPIRE,
  NETWORK_QUIC_DATA,
  NETWORK_QUIC_CONNECTED,
  NETWORK_QUIC_DISCONNECTED
} message_type_e;

typedef struct message_t {
  uint32_t type;
  void* payload;
  void (*payload_destroy)(void*);
} message_t;

#endif // OFFS_MESSAGE_H
