//
// Created by victor on 5/6/25.
//

#ifndef OFFS_MESSAGE_H
#define OFFS_MESSAGE_H

#include <stdint.h>

typedef enum message_type_e {
  SECTION_WRITE = 0,
  SECTION_READ,
  SECTION_DEALLOCATE,
  SECTION_SAVE_META,
  SECTION_CLOSE,
  SECTIONS_WRITE,
  SECTIONS_READ,
  SECTIONS_DEALLOCATE,
  SECTIONS_SECTION_FULL,
  SECTIONS_WRITE_COMPLETE,
  SECTIONS_READ_COMPLETE,
  SECTIONS_DEALLOCATE_COMPLETE,
  CACHE_GET,
  CACHE_PUT,
  CACHE_REMOVE,
  CACHE_BLOCK_LOADED,
  TIMER_SET,
  TIMER_CANCEL,
  TIMER_DEBOUNCE,
  INDEX_SAVE,
  SECTION_WRITE_META,
  READABLE_PUSH,
  READABLE_READ,
  READABLE_READ_COMPLETE,
  WRITEABLE_WRITE,
  CLOSE_STREAM,
  READABLE_PULL,
  DEFERRED_DEREF,
  TUPLE_CACHE_GET,
  TUPLE_CACHE_PUT,
  TUPLE_CACHE_REMOVE,
  TUPLE_CACHE_CONTAINS,
  TUPLE_CACHE_SIZE,
  OFF_STREAM_WRITE,
  WRITEABLE_FINALIZE,
  WRITEABLE_DESCRIPTOR_WRITE,
  BLOCK_RECIPE_PULL,
  RECIPE_BLOCK_DATA,
  RECIPE_ROTATE,
  SECTION_WRITE_COMPLETE,
  SECTION_READ_COMPLETE,
  SECTION_DEALLOCATE_COMPLETE,
  STREAM_NOTIFY,
  /* Async result messages — sent back to reply_to actor */
  SECTION_READ_RESULT,
  SECTION_WRITE_RESULT,
  SECTION_DEALLOCATE_RESULT,
  SECTIONS_READ_RESULT,
  SECTIONS_WRITE_RESULT,
  SECTIONS_DEALLOCATE_RESULT,
  CACHE_GET_RESULT,
  CACHE_PUT_RESULT,
  CACHE_REMOVE_RESULT,
  TUPLE_CACHE_GET_RESULT
} message_type_e;

typedef struct message_t {
  uint32_t type;
  void* payload;
  void (*payload_destroy)(void*);
} message_t;

#endif // OFFS_MESSAGE_H
